name: adult-income-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas>=2.2.0
      - numpy>=2.0.0
      - scikit-learn>=1.5.0
      - matplotlib>=3.8.0
      - joblib>=1.3.0
      - dagshub>=0.4.0
